### ISSUE TITLE
Unable to locate keystore.properties

### ISSUE THREAD

**Issue by luharinos** [vanyaland/Habito#38]
The application cannot be configured in the [Android Studio](https://developer.android.com/studio/), it raises the following error before the build process. Kindly update the _**README.md**_ to properly configure it to the [Android Studio](https://developer.android.com/studio/) for further development.

``Error: AndroidStudioProjects/Habito/keystore.properties (No such file or directory)``

**Comment by ivan-magda** [comment]
@raoniz , please check if it now work for you.

**Comment by luharinos** [comment]
The issue has been resolved, the application can be successfully configured and built in [Android Studio](https://developer.android.com/studio/).

**Comment by ivan-magda** [comment]
@raoniz thanks !

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
