### ISSUE TITLE
Icon Logo

### ISSUE THREAD

**Issue by mendezand** [vanyaland/Habito#39]
Hi.
If you want I can support with Habito designs. I can create a logo if you wish, designed for Android's adaptive icons.

Regards.

**Comment by ivan-magda** [comment]
Hey, @mendezand ! Yes, I would, that would be great 🥇 You are free in design, do as you want.

Thanks a lot.

**Comment by ivan-magda** [comment]
Assigns to you.

**Comment by mendezand** [comment]
I will be working on it. Sorry I was a little busy.

**Comment by mendezand** [comment]
Do you like how is it going or do you want some modification?
![image](https://user-images.githubusercontent.com/38763253/40392135-902736f0-5de8-11e8-9d04-72e73b130cda.png)

**Comment by ivan-magda** [comment]
@mendezand great progress!

Take a look at the [color scheme](https://github.com/vanyaland/Habito/blob/master/app/src/main/res/values/colors.xml) of the application, better to use *primary* colors.

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="colorPrimary">#2196F3</color>
    <color name="colorPrimaryDark">#1976D2</color>
    <color name="colorPrimaryLight">#BBDEFB</color>
    <color name="colorAccent">#FF4081</color>
    <color name="white">#FFFFFF</color>

    <color name="primary_text">#212121</color>
    <color name="secondary_text">#757575</color>

    <!-- The activated state color for a habit list item -->
    <color name="activated">#E0E0E0</color>
</resources>
```

Also, this objects outside of the main circle icon looks a little bit strange. Move inside of the circle or remove them.

Several other habit tracker logos to look at:
- [Dribble](https://dribbble.com/search?q=habit)
- [HabitHub](https://play.google.com/store/apps/details?id=com.rstudioz.habits)
- [habitbull](https://play.google.com/store/apps/details?id=com.oristats.habitbull)
- [uhabits](https://play.google.com/store/apps/details?id=org.isoron.uhabits)
- [habitica](https://play.google.com/store/apps/details?id=com.habitrpg.android.habitica)

**Comment by mendezand** [comment]
I see that you want something simpler and more representative.

**Comment by mendezand** [comment]
What do you think of this style?
![image](https://user-images.githubusercontent.com/38763253/40619482-33adce3c-6263-11e8-88a0-8969748e86a6.png)

I used "H" and a loop. Because habits can be repeated daily.

**Comment by ivan-magda** [comment]
@mendezand yep, this looks better.
What color will be the background? How about white?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mendezand** [comment]
Yes. I thought of a soft white gradient.

**Comment by mendezand** [comment]
U like it?
![image](https://user-images.githubusercontent.com/38763253/40629282-1bfe1f46-6298-11e8-82fa-3f2b4659dfdc.png)

**Comment by ivan-magda** [comment]
@mendezand looks awesome!
What about increasing the white color channel of the background, maybe this will looks better?

But I already like it 👍

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mendezand** [comment]
Better?
![image](https://user-images.githubusercontent.com/38763253/40630048-48c746c4-629d-11e8-8059-3639c4e55f88.png)

**Comment by ivan-magda** [comment]
@mendezand yes.

Now you need [generate](https://developer.android.com/studio/write/image-asset-studio) launch image asset and apply new icons.
Then we are able to merge 🎉

**Comment by mendezand** [comment]
[Here](https://drive.google.com/file/d/1uTTf0ig84ik6pG7SZdksUp21JRdABZdH/view?usp=sharing) are the editable design files.

I will create the PR of the designs.
